export const AVAILABLE_SYNTAX = [
	{name: "ABAP", value: "abap"},
	{name: "ABNF", value: "abnf"},
	{name: "ActionScript", value: "actionscript"},
	{name: "Ada", value: "ada"},
	{name: "Agda", value: "agda"},
	{name: "AL", value: "al"},
	{name: "ANTLR 4", value: "antlr4"},
	{name: "Apache Conf", value: "apacheconf"},
	{name: "Apex", value: "apex"},
	{name: "APL", value: "apl"},
	{name: "AppleScript", value: "applescript"},
	{name: "AQL", value: "aql"},
	{name: "ARFF", value: "arff"},
	{name: "AsciiDoc", value: "asciidoc"},
	{name: "Assembler 6502", value: "asm6502"},
	{name: "ASP.NET", value: "aspnet"},
	{name: "Atom", value: "atom"},
	{name: "AutoHotKey", value: "autohotkey"},
	{name: "AutoIt", value: "autoit"},
	{name: "Bash", value: "bash"},
	{name: "BASIC", value: "basic"},
	{name: "Batch", value: "batch"},
	{name: "BBCode", value: "bbcode"},
	{name: "Birb", value: "birb"},
	{name: "BNF", value: "bnf"},
	{name: "Brainf*ck", value: "brainfuck"},
	{name: "BrightScript", value: "brightscript"},
	{name: "Bro", value: "bro"},
	{name: "BSL", value: "bsl"},
	{name: "C", value: "c"},
	{name: "CFScript", value: "cfscript"},
	{name: "CIL", value: "cil"},
	{name: "C-like", value: "clike"},
	{name: "Clojure", value: "clojure"},
	{name: "CMake", value: "cmake"},
	{name: "COBOL", value: "cobol"},
	{name: "CoffeeScript", value: "coffeescript"},
	{name: "Concurnas", value: "concurnas"},
	{name: "Coq", value: "coq"},
	{name: "C++", value: "cpp"},
	{name: "C#", value: "csharp"},
	{name: "CSP", value: "csp"},
	{name: "CSS", value: "css"},
	{name: "CSS extras", value: "css-extras"},
	{name: "CSV", value: "csv"},
	{name: "Cypher", value: "cypher"},
	{name: "D", value: "d"},
	{name: "Dart", value: "dart"},
	{name: "DataWeave", value: "dataweave"},
	{name: "DAX", value: "dax"},
	{name: "Dhall", value: "dhall"},
	{name: "Diff", value: "diff"},
	{name: "DNS zone file", value: "dns-zone-file"},
	{name: "Docker", value: "docker"},
	{name: "DOT", value: "dot"},
	{name: "EBNF", value: "ebnf"},
	{name: "EditorConfig", value: "editorconfig"},
	{name: "Eiffel", value: "eiffel"},
	{name: "EJS", value: "ejs"},
	{name: "Elixir", value: "elixir"},
	{name: "Elm", value: "elm"},
	{name: "Embedded Ruby (eRB)", value: "erb"},
	{name: "Erlang", value: "erlang"},
	{name: "Embedded Lua (etLua)", value: "etlua"},
	{name: "Excel Formula", value: "excel-formula"},
	{name: "Factor", value: "factor"},
	{name: "FALSE", value: "false"},
	{name: "FireStore Security Rules", value: "firestore-security-rules"},
	{name: "FLOW", value: "flow"},
	{name: "Fortran", value: "fortran"},
	{name: "F#", value: "fsharp"},
	{name: "FreeMarker Template Language (FTL)", value: "ftl"},
	{name: "G-Code", value: "gcode"},
	{name: "GDScript", value: "gdscript"},
	{name: "GEDCOM", value: "gedcom"},
	{name: "Gherkin", value: "gherkin"},
	{name: "Git", value: "git"},
	{name: "OpenGL Shading Language (GLSL)", value: "glsl"},
	{name: "Game Maker Language (GML)", value: "gml"},
	{name: "Go (golang)", value: "go"},
	{name: "GraphQL", value: "graphql"},
	{name: "Apache Groovy", value: "groovy"},
	{name: "Haml", value: "haml"},
	{name: "Handlebars", value: "handlebars"},
	{name: "HashiCorp Configuration Language (HCL)", value: "hcl"},
	{name: "Haskell", value: "haskell"},
	{name: "Haxe", value: "haxe"},
	{name: "High-Level Shading Language (HLSL)", value: "hlsl"},
	{name: "HTML", value: "html"},
	{name: "HTTP Public Key Pinning (HPKP)", value: "hpkp"},
	{name: "HTTP Strict Transport Security (HSTS)", value: "hsts"},
	{name: "HTTP", value: "http"},
	{name: "IchigoJam", value: "ichigojam"},
	{name: "Icon", value: "icon"},
	{name: "ICU message format", value: "icu-message-format"},
	{name: "Idris", value: "idris"},
	{name: "IEC 61131-3 ST", value: "iecst"},
	{name: "Ignore files (.gitignore, etc.)", value: "ignore"},
	{name: "Inform 7", value: "inform7"},
	{name: "INI", value: "ini"},
	{name: "Io", value: "io"},
	{name: "J", value: "j"},
	{name: "Java", value: "java"},
	{name: "JavaDoc-like", value: "javadoclike"},
	{name: "JavaScript", value: "javascript"},
	{name: "Java stack trace", value: "javastacktrace"},
	{name: "Java Expression Language (JEXL)", value: "jexl"},
	{name: "Jolie", value: "jolie"},
	{name: "jq", value: "jq"},
	{name: "JS Extras", value: "js-extras"},
	{name: "JS Templates", value: "js-templates"},
	{name: "JSON", value: "json"},
	{name: "JSON5", value: "json5"},
	{name: "JSON-P", value: "jsonp"},
	{name: "JS stacktrace", value: "jsstacktrace"},
	{name: "JSX", value: "jsx"},
	{name: "Julia", value: "julia"},
	{name: "Keyman Keyboard Language", value: "keyman"},
	{name: "Kotlin", value: "kotlin"},
	{name: "KuMir", value: "kumir"},
	{name: "LaTeX", value: "latex"},
	{name: "Latte", value: "latte"},
	{name: "Less", value: "less"},
	{name: "LilyPond", value: "lilypond"},
	{name: "Liquid", value: "liquid"},
	{name: "Lisp", value: "lisp"},
	{name: "LiveScript", value: "livescript"},
	{name: "LLVM", value: "llvm"},
	{name: "Log files", value: "log"},
	{name: "LOLCODE", value: "lolcode"},
	{name: "Lua", value: "lua"},
	{name: "Makefile", value: "makefile"},
	{name: "Markdown", value: "markdown"},
	{name: "Markup", value: "markup"},
	{name: "Markup templating", value: "markup-templating"},
	{name: "MathML", value: "mathml"},
	{name: "MATLAB", value: "matlab"},
	{name: "Maya Embedded Language (MEL)", value: "mel"},
	{name: "Mizar", value: "mizar"},
	{name: "MongoDB", value: "mongodb"},
	{name: "Monkey", value: "monkey"},
	{name: "MoonScript", value: "moonscript"},
	{name: "N1QL", value: "n1ql"},
	{name: "N4JS", value: "n4js"},
	{name: "Nand2Tetris HDL", value: "nand2tetris-hdl"},
	{name: "NaniScript", value: "naniscript"},
	{name: "Neon", value: "neon"},
	{name: "Netwide Assembler (NASM)", value: "nasm"},
	{name: "Nevod", value: "nevod"},
	{name: "NGINX", value: "nginx"},
	{name: "Nim", value: "nim"},
	{name: "Nix", value: "nix"},
	{name: "NSIS", value: "nsis"},
	{name: "Objective C", value: "objectivec"},
	{name: "OCaml", value: "ocaml"},
	{name: "OpenQASM", value: "openqasm"},
	{name: "Oz", value: "oz"},
	{name: "PARI/GP", value: "parigp"},
	{name: "Parser", value: "parser"},
	{name: "Pascal", value: "pascal"},
	{name: "PascaLIGO", value: "pascaligo"},
	{name: "PC-Axis", value: "pcaxis"},
	{name: "PeopleCode", value: "peoplecode"},
	{name: "Perl", value: "perl"},
	{name: "PHP", value: "php"},
	{name: "PHP Extras", value: "php-extras"},
	{name: "PowerQuery", value: "powerquery"},
	{name: "PowerShell", value: "powershell"},
	{name: "Processing", value: "processing"},
	{name: "Prolog", value: "prolog"},
	{name: "PromQL", value: "promql"},
	{name: ".properties file", value: "properties"},
	{name: "Protocol Buffers", value: "protobuf"},
	{name: "Profile Scripting Language (PSL)", value: "psl"},
	{name: "Pug", value: "pug"},
	{name: "Puppet", value: "puppet"},
	{name: "Pure", value: "pure"},
	{name: "PureBasic", value: "purebasic"},
	{name: "Python", value: "python"},
	{name: "Q", value: "q"},
	{name: "QML", value: "qml"},
	{name: "Qore", value: "qore"},
	{name: "Q#", value: "qsharp"},
	{name: "R", value: "r"},
	{name: "Reason", value: "reason"},
	{name: "RegEx", value: "regex"},
	{name: "Rego", value: "rego"},
	{name: "RenPy", value: "renpy"},
	{name: "REST", value: "rest"},
	{name: "Rip", value: "rip"},
	{name: "Roboconf", value: "roboconf"},
	{name: "Robot Framework", value: "robotframework"},
	{name: "RSS", value: "rss"},
	{name: "Ruby", value: "ruby"},
	{name: "Rust", value: "rust"},
	{name: "SAS", value: "sas"},
	{name: "SASS", value: "sass"},
	{name: "Scheme", value: "scheme"},
	{name: "SCSS", value: "scss"},
	{name: "Shell session", value: "shell-session"},
	{name: "Smali", value: "smali"},
	{name: "Smalltalk", value: "smalltalk"},
	{name: "Smarty", value: "smarty"},
	{name: "Standard ML (SML)", value: "sml"},
	{name: "Solidity", value: "solidity"},
	{name: "Solution files", value: "solution-file"},
	{name: "Soy", value: "soy"},
	{name: "Splunk SPL", value: "splunk-spl"},
	{name: "SQF", value: "sqf"},
	{name: "SQL", value: "sql"},
	{name: "Squirrel", value: "squirrel"},
	{name: "SSML", value: "ssml"},
	{name: "Stan", value: "stan"},
	{name: "Stylus", value: "stylus"},
	{name: "SVG", value: "svg"},
	{name: "Swift", value: "swift"},
	{name: "Test Anything Protocol (TAP)", value: "tap"},
	{name: "Tcl", value: "tcl"},
	{name: "Textile", value: "textile"},
	{name: "TOML", value: "toml"},
	{name: "TapTitans2 (TT2)", value: "tt2"},
	{name: "Turtle", value: "turtle"},
	{name: "Twig", value: "twig"},
	{name: "TypeScript", value: "typescript"},
	{name: "TypoScript", value: "typoscript"},
	{name: "UnrealScript", value: "unrealscript"},
	{name: "URI", value: "uri"},
	{name: "V", value: "v"},
	{name: "Vala", value: "vala"},
	{name: "Apache Velocity", value: "velocity"},
	{name: "Verilog", value: "verilog"},
	{name: "VHDL", value: "vhdl"},
	{name: "Vim", value: "vim"},
	{name: "Visual Basic", value: "visual-basic"},
	{name: "WarpScript", value: "warpscript"},
	{name: "WebAssembly", value: "wasm"},
	{name: "Wiki", value: "wiki"},
	{name: "Wolfram", value: "wolfram"},
	{name: "Xeora", value: "xeora"},
	{name: "XML", value: "xml"},
	{name: "XML Doc", value: "xml-doc"},
	{name: "Xojo", value: "xojo"},
	{name: "XQuery", value: "xquery"},
	{name: "YAML", value: "yaml"},
	{name: "YANG", value: "yang"},
	{name: "Zig", value: "zig"},
];